project: 
  type: website
  output-dir: docs

book:
  title: "Homework4"
  author: "Aly, Haley & Zoe"
  date: "4/19/2023"
  chapters:
    - index.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

